# Generated by Django 6.0.3 on 2026-04-12 16:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Workspace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True)),
                ('codigo', models.CharField(blank=True, max_length=8, unique=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspaces_admin', to=settings.AUTH_USER_MODEL)),
                ('miembros', models.ManyToManyField(blank=True, related_name='workspaces_miembro', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Espacio de Trabajo',
                'verbose_name_plural': 'Espacios de Trabajo',
                'ordering': ['-creado_en'],
            },
        ),
    ]
