# Generated by Django 6.0.3 on 2026-04-03 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tareas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tareas',
            options={'ordering': ['-creado_en'], 'verbose_name': 'Tarea', 'verbose_name_plural': 'Tareas'},
        ),
        migrations.RenameField(
            model_name='tareas',
            old_name='fecha_creacion',
            new_name='creado_en',
        ),
        migrations.RemoveField(
            model_name='tareas',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='tareas',
            name='fecha_limite',
        ),
        migrations.AddField(
            model_name='tareas',
            name='completada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tareas',
            name='fecha_vencimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tareas',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='tareas',
            name='prioridad',
            field=models.CharField(choices=[('A', 'Alta'), ('M', 'Media'), ('B', 'Baja')], default='M', max_length=1),
        ),
        migrations.AlterField(
            model_name='tareas',
            name='titulo',
            field=models.CharField(max_length=255),
        ),
    ]
