# Generated by Django 6.0.3 on 2026-04-12 14:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tareas', '0002_alter_tareas_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EspacioTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Equipo')),
                ('codigo', models.CharField(default='D270CB37', editable=False, max_length=8, unique=True, verbose_name='Código de Acceso')),
                ('administrador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mis_equipos', to=settings.AUTH_USER_MODEL, verbose_name='Creador del Equipo')),
            ],
            options={
                'verbose_name': 'Espacio de Trabajo',
                'verbose_name_plural': 'Espacios de Trabajo',
            },
        ),
        migrations.AddField(
            model_name='tareas',
            name='espacio_trabajo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tareas_equipo', to='Tareas.espaciotrabajo', verbose_name='Equipo'),
        ),
    ]
