# Generated by Django 6.0.3 on 2026-04-01 15:58

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tareas', '0002_remove_tareas_categoria_categoria_tarea_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categoria',
            new_name='Categorias',
        ),
        migrations.RenameModel(
            old_name='Tarea',
            new_name='Tareas',
        ),
    ]
