# Generated by Django 6.0.3 on 2026-04-13 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tareas', '0003_tareas_workspace'),
    ]

    operations = [
        migrations.AddField(
            model_name='tareas',
            name='estado',
            field=models.CharField(choices=[('TODO', 'Por Hacer'), ('PROG', 'En Progreso'), ('DONE', 'Completada')], default='TODO', max_length=4),
        ),
    ]
