# Generated by Django 6.0.3 on 2026-04-02 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tareas', '0004_alter_tareas_categoria_remove_tareas_prioridad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tareas',
            name='prioridad',
            field=models.CharField(choices=[('Baja', 'Baja'), ('Media', 'Media'), ('Alta', 'Alta')], default='Baja', max_length=10),
        ),
    ]
