# Generated by Django 6.0.3 on 2026-04-13 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tareas', '0004_tareas_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='tareas',
            name='en_progreso',
            field=models.BooleanField(default=False),
        ),
    ]
