# Generated by Django 6.0.3 on 2026-04-03 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorias',
            options={'ordering': ['nombre'], 'verbose_name': 'Categoría', 'verbose_name_plural': 'Categorías'},
        ),
        migrations.RemoveField(
            model_name='categorias',
            name='prioridad',
        ),
        migrations.AlterField(
            model_name='categorias',
            name='color',
            field=models.CharField(default='#10b981', max_length=7),
        ),
    ]
