# Generated by Django 6.0.3 on 2026-04-02 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0003_alter_categorias_prioridad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorias',
            name='color',
            field=models.CharField(default='#3498db', max_length=7),
        ),
    ]
